/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef EDITOR_API
#define EDITOR_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern EDITOR_API FName EDITOR_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(Build)

#ifndef NAMES_ONLY


class EDITOR_API UOptionsProxy : public UObject
{
public:
    FStringNoInit DlgCaption;
    DECLARE_CLASS(UOptionsProxy,UObject,0)
    NO_DEFAULT_CONSTRUCTOR(UOptionsProxy)
};


class EDITOR_API UOptionsSurfBevel : public UOptionsProxy
{
public:
    INT Depth;
    INT Bevel;
    DECLARE_CLASS(UOptionsSurfBevel,UOptionsProxy,0)
    NO_DEFAULT_CONSTRUCTOR(UOptionsSurfBevel)
};


class EDITOR_API UOptions2DShaperBezierDetail : public UOptionsProxy
{
public:
    INT DetailLevel;
    DECLARE_CLASS(UOptions2DShaperBezierDetail,UOptionsProxy,0)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperBezierDetail)
};

enum EAxis
{
    AXIS_X                  =0,
    AXIS_Y                  =1,
    AXIS_Z                  =2,
    AXIS_MAX                =3,
};

class EDITOR_API UOptions2DShaper : public UOptionsProxy
{
public:
    BYTE Axis;
    DECLARE_CLASS(UOptions2DShaper,UOptionsProxy,0)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaper)
};


class EDITOR_API UOptions2DShaperRevolve : public UOptions2DShaper
{
public:
    INT Per360;
    INT Use;
    DECLARE_CLASS(UOptions2DShaperRevolve,UOptions2DShaper,0)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperRevolve)
};


class EDITOR_API UOptions2DShaperSheet : public UOptions2DShaper
{
public:
    DECLARE_CLASS(UOptions2DShaperSheet,UOptions2DShaper,0)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperSheet)
};


class EDITOR_API UOptions2DShaperExtrudeToBevel : public UOptions2DShaper
{
public:
    FLOAT Height;
    FLOAT CapHeight;
    DECLARE_CLASS(UOptions2DShaperExtrudeToBevel,UOptions2DShaper,0)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperExtrudeToBevel)
};


class EDITOR_API UOptions2DShaperExtrudeToPoint : public UOptions2DShaper
{
public:
    FLOAT Depth;
    DECLARE_CLASS(UOptions2DShaperExtrudeToPoint,UOptions2DShaper,0)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperExtrudeToPoint)
};


class EDITOR_API UOptions2DShaperExtrude : public UOptions2DShaper
{
public:
    FLOAT Depth;
    DECLARE_CLASS(UOptions2DShaperExtrude,UOptions2DShaper,0)
    NO_DEFAULT_CONSTRUCTOR(UOptions2DShaperExtrude)
};

enum ETAxis
{
    TAXIS_X                 =0,
    TAXIS_Y                 =1,
    TAXIS_Z                 =2,
    TAXIS_AUTO              =3,
    TAXIS_WALLS             =4,
    TAXIS_MAX               =5,
};

class EDITOR_API UOptionsTexAlign : public UOptionsProxy
{
public:
    BYTE TAxis;
    DECLARE_CLASS(UOptionsTexAlign,UOptionsProxy,0)
    NO_DEFAULT_CONSTRUCTOR(UOptionsTexAlign)
};


class EDITOR_API UOptionsTexAlignPlanar : public UOptionsTexAlign
{
public:
    DECLARE_CLASS(UOptionsTexAlignPlanar,UOptionsTexAlign,0)
    NO_DEFAULT_CONSTRUCTOR(UOptionsTexAlignPlanar)
};


class EDITOR_API UOptionsTexAlignFace : public UOptionsProxy
{
public:
    FLOAT TileU;
    FLOAT TileV;
    DECLARE_CLASS(UOptionsTexAlignFace,UOptionsProxy,0)
    NO_DEFAULT_CONSTRUCTOR(UOptionsTexAlignFace)
};


class EDITOR_API UOptionsBrushScale : public UOptionsProxy
{
public:
    FLOAT X;
    FLOAT Y;
    FLOAT Z;
    DECLARE_CLASS(UOptionsBrushScale,UOptionsProxy,0)
    NO_DEFAULT_CONSTRUCTOR(UOptionsBrushScale)
};


struct UBrushBuilder_eventBuild_Parms
{
    BITFIELD ReturnValue;
};
class EDITOR_API UBrushBuilder : public UObject
{
public:
    FStringNoInit BitmapFilename;
    FStringNoInit ToolTip;
    TArray<FVector> Vertices;
    TArray<FBuilderPoly> Polys;
    FName Group;
    BITFIELD MergeCoplanars:1 GCC_PACK(4);
    DECLARE_FUNCTION(execPolyEnd);
    DECLARE_FUNCTION(execPolyi);
    DECLARE_FUNCTION(execPolyBegin);
    DECLARE_FUNCTION(execPoly4i);
    DECLARE_FUNCTION(execPoly3i);
    DECLARE_FUNCTION(execVertex3f);
    DECLARE_FUNCTION(execVertexv);
    DECLARE_FUNCTION(execBadParameters);
    DECLARE_FUNCTION(execGetPolyCount);
    DECLARE_FUNCTION(execGetVertex);
    DECLARE_FUNCTION(execGetVertexCount);
    DECLARE_FUNCTION(execEndBrush);
    DECLARE_FUNCTION(execBeginBrush);
    inline BITFIELD __fastcall eventBuild()
    {
        UBrushBuilder_eventBuild_Parms Parms;
        Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(EDITOR_Build),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UBrushBuilder,UObject,0)
    #include "UBrushBuilder.h"
};

#endif

AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyEnd);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyi);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyBegin);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly4i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly3i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertex3f);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertexv);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBadParameters);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetPolyCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertex);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertexCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execEndBrush);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBeginBrush);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
