//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MacEdit.rc
//
#define IDD_WIN_INPUTBOX                103
#define IDD_WIN_SELECTIONBOX            104
#define IDD_WIN_VECTORBOX               105
#define IDD_WIN_SELECTIONBOXMULTI       106
#define IDD_MACEDIT                     111
#define IDD_MAC_BROWSER                 111
#define IDD_MAC_EDITOR                  111
#define IDM_MACEDIT                     112
#define IDB_FILE_OPEN                   114
#define IDB_FILE_CLOSED                 115
#define IDB_CPJ_MAC                     116
#define IDB_CPJ_CPJ                     117
#define IDB_CPJ_GEO                     118
#define IDB_CPJ_SRF                     119
#define IDB_CPJ_LOD                     121
#define IDB_CPJ_SKL                     122
#define IDB_CPJ_FRM                     123
#define IDB_CPJ_SEQ                     124
#define IDM_MACTREEPOPUPS               125
#define IDM_MAC_TREEPOPUPS              125
#define IDD_MAC_BR_MAC                  126
#define IDD_MAC_PR_MAC                  126
#define IDD_MAC_BR_GEO                  127
#define IDD_MAC_PR_GEO                  127
#define IDD_MAC_BR_SRF                  128
#define IDD_MAC_PR_SRF                  128
#define IDD_MAC_BR_SKL                  129
#define IDD_MAC_PR_SKL                  129
#define IDD_MAC_BR_LOD                  130
#define IDD_MAC_PR_LOD                  130
#define IDD_MAC_BR_FRM                  131
#define IDD_MAC_PR_FRM                  131
#define IDD_MAC_BR_SEQ                  132
#define IDD_MAC_PR_SEQ                  132
#define IDC_ST_WIN_INPUTBOX             1001
#define IDC_ST_WIN_SELECTIONBOX         1001
#define IDC_ST_WIN_VECTORBOX_X          1001
#define IDC_EB_WIN_INPUTBOX             1002
#define IDC_LB_WIN_SELECTIONBOX         1002
#define IDC_EB_WIN_VECTORBOX_X          1002
#define IDC_ST_WIN_VECTORBOX_Y          1003
#define IDC_EB_WIN_VECTORBOX_Y          1004
#define IDC_ST_WIN_VECTORBOX_Z          1005
#define IDC_EB_WIN_VECTORBOX_Z          1006
#define IDC_TV_BROWSER                  1010
#define IDC_TV_MAC_BROWSER              1010
#define IDC_LV_CONFIG                   1011
#define IDC_EB_MAC_GEOMETRY             1016
#define IDC_BT_MAC_CLEARGEO             1017
#define IDC_EB_MAC_SURFACE0             1018
#define IDC_BT_MAC_CLEARSRF0            1019
#define IDC_EB_MAC_SURFACE1             1020
#define IDC_BT_MAC_CLEARSRF1            1021
#define IDC_EB_MAC_SKELETON             1022
#define IDC_BT_MAC_CLEARSKL             1023
#define IDC_EB_MAC_LODDATA              1024
#define IDC_BT_MAC_CLEARLOD             1025
#define IDC_EB_MAC_CONFIG               1026
#define IDC_BT_MAC_CLEARFRM             1027
#define IDC_CB_MAC_FRAMES_FILES         1028
#define IDC_EB_MAC_AUTHOR               1029
#define IDC_CB_MAC_SEQUENCES_FILES      1030
#define IDC_BT_MAC_CLEARSEQ             1031
#define IDC_CB_MAC_SEQUENCES_OBJECTS    1032
#define IDC_CB_MAC_FRAMES_OBJECTS       1033
#define IDC_BT_MAC_CONFIGSAVE           1034
#define IDC_BT_MAC_CONFIGSAVEAS         1035
#define IDC_CK_MAC_CONFIGSAVECPJ        1036
#define IDC_EB_MAC_DESCRIPTION          1037
#define IDC_BT_MAC_ORIGIN               1039
#define IDC_ST_MAC_ORIGIN               1040
#define IDC_BT_MAC_SCALE                1041
#define IDC_ST_MAC_SCALE                1042
#define IDC_BT_MAC_ROTATION             1043
#define IDC_ST_MAC_ROTATION             1044
#define IDC_LB_MAC_PR_MAC_COMMANDS      1044
#define IDC_BT_MAC_BBMIN                1045
#define IDC_EB_MAC_PR_GEO_NUMVERTS      1045
#define IDC_ST_MAC_BBMIN                1046
#define IDC_EB_MAC_PR_GEO_NUMTRIS       1046
#define IDC_BT_MAC_BBMAX                1047
#define IDC_ST_MAC_BBMAX                1048
#define IDC_EB_MAC_PR_GEO_NUMMOUNTS     1048
#define IDC_EB_MAC_PR_GEO_NUMVERTSLOCKED 1049
#define IDC_BT_MAC_REFRESH              1049
#define IDC_CB_MAC_PR_GEO_MOUNTS        1050
#define IDC_BT_MAC_BBAUTO               1050
#define IDC_BT_MAC_PR_GEO_MOUNTRENAME   1051
#define IDC_BT_MAC_AUTOCENTER           1051
#define IDC_EB_MAC_PR_SRF_NUMTEXTURES   1054
#define IDC_EB_MAC_PR_SRF_NUMTRIS       1055
#define IDC_EB_MAC_PR_SRF_NUMUV         1056
#define IDC_CB_MAC_PR_SRF_TEXTURES      1057
#define IDC_BT_MAC_PR_SRF_TEXTURERENAME 1058
#define IDC_EB_MAC_PR_SRF_TEXTUREOBJ    1059
#define IDC_BT_MAC_PR_SRF_TEXTUREOBJUSE 1060
#define IDC_BT_MAC_PR_LOD_GENERATE      1060
#define IDC_EB_MAC_PR_FRM_NUMFRAMES     1061
#define IDC_LB_MAC_PR_FRM_FRAMES        1062
#define IDC_EB_MAC_PR_FRM_FRAMENUMVERTS 1063
#define IDC_CK_MAC_PR_FRM_FRAMECOMPRESSED 1064
#define IDC_EB_MAC_PR_SKL_NUMVERTS      1065
#define IDC_EB_MAC_PR_SKL_NUMWEIGHTS    1066
#define IDC_EB_MAC_PR_SKL_NUMMOUNTS     1067
#define IDC_CB_MAC_PR_SKL_MOUNTS        1068
#define IDC_BT_MAC_PR_SKL_MOUNTRENAME   1069
#define IDC_CB_MAC_PR_SKL_BONES         1070
#define IDC_EB_MAC_PR_SEQ_NUMFRAMES     1070
#define IDC_BT_MAC_PR_SKL_BONERENAME    1071
#define IDC_EB_MAC_PR_SEQ_NUMBONES      1071
#define IDC_EB_MAC_PR_SKL_NUMBONES      1072
#define IDC_CB_MAC_PR_SEQ_BONES         1072
#define IDC_BT_WIN_SELECTIONBOXMULTI_SELALL 1072
#define IDC_EB_MAC_PR_SKL_BONEPARENT    1073
#define IDC_CB_MAC_PR_SEQ_EVENTTYPE     1073
#define IDC_BT_WIN_SELECTIONBOXMULTI_SELNONE 1073
#define IDC_EB_MAC_PR_SKL_BONELENGTH    1074
#define IDC_BT_MAC_PR_SEQ_EVENTADD      1074
#define IDC_EB_MAC_PR_SEQ_EVENTTIME     1075
#define IDC_EB_MAC_PR_SEQ_NUMEVENTS     1076
#define IDC_EB_MAC_PR_SEQ_EVENTSTRING   1077
#define IDC_EB_MAC_PR_SEQ_CUREVENT      1078
#define IDC_BT_MAC_PR_SEQ_EVENTDELETE   1079
#define IDC_BT_MAC_PR_SEQ_EVENTPREV     1080
#define IDC_BT_MAC_PR_SEQ_EVENTNEXT     1081
#define IDC_EB_MAC_PR_SEQ_PLAYRATE      1082
#define IDC_BT_MAC_PR_SEQ_PLAYRATE      1083
#define IDC_BT_MAC_PR_SEQ_BONEREMOVE    1084
#define ID_MAC_CHUNK_RENAME             40005
#define ID_MAC_CHUNK_IMPORT             40006
#define ID_MAC_CHUNK_EXPORT             40007
#define ID_MAC_CHUNK_DELETE             40008
#define ID_MAC_PROJECT_EXPAND           40009
#define ID_MAC_PROJECT_DELETE           40010
#define ID_MAC_FOLDER_DELETE            40011
#define ID_MAC_FOLDER_RENAME            40012
#define ID_MAC_FOLDER_NEW_FOLDER        40013
#define ID_MAC_FOLDER_NEW_PROJECT       40014
#define ID_MAC_PROJECT_SAVE             40015
#define ID_MAC_PROJECT_NEW_CONFIG       40018
#define ID_MAC_PROJECT_NEW_GEOMETRY     40019
#define ID_MAC_PROJECT_NEW_SURFACE      40020
#define ID_MAC_PROJECT_NEW_SKELETON     40021
#define ID_MAC_PROJECT_NEW_LODDATA      40022
#define ID_MAC_PROJECT_NEW_FRAMES       40023
#define ID_MAC_PROJECT_NEW_SEQUENCE     40024
#define ID_MAC_PROJECT_IMPORT           40025
#define ID_MAC_PROJECT_EXPORT           40026
#define ID_MAC_PROJECT_RENAME           40027
#define ID_MAC_GEOMETRY_USE             40028
#define ID_MAC_LODDATA_USE              40029
#define ID_MAC_SKELETON_USE             40030
#define ID_MAC_FRAMES_USE               40031
#define ID_MAC_SEQUENCE_USE             40032
#define ID_MAC_SURFACE_USE_PRIMARY      40033
#define ID_MAC_SURFACE_USE_DECAL        40034
#define ID_MAC_CONFIG_LOAD              40035
#define ID_MAC_CONFIG_SAVE              40036
#define ID_MAC_PROJECT_USE_FRAMES       40037
#define ID_MAC_PROJECT_USE_SEQUENCES    40038
#define ID_MAC_FOLDER_USE_FRAMES        40039
#define ID_MAC_FOLDER_USE_SEQUENCES     40040
#define ID_MAC_CHUNK_DETAILS            40041
#define ID_MAC_CONFIG_USE               40042
#define ID_MAC_PROJECT_REMOVE_CONFIG    40043
#define ID_MAC_PROJECT_REMOVE_FRAMES    40044
#define ID_MAC_PROJECT_REMOVE_GEOMETRY  40045
#define ID_MAC_PROJECT_REMOVE_LODDATA   40046
#define ID_MAC_PROJECT_REMOVE_SEQUENCE  40047
#define ID_MAC_PROJECT_REMOVE_SKELETON  40048
#define ID_MAC_PROJECT_REMOVE_SURFACE   40049
#define ID_MAC_PROJECT_IMPORT_FRAMES    40050
#define ID_MAC_PROJECT_IMPORT_SEQUENCES 40051

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        128
#define _APS_NEXT_COMMAND_VALUE         40052
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
